const fs = require('fs');
const path = require('path');

/**
 * Parses the YAML frontmatter from an agent markdown file.
 * Returns { name, description } or falls back to the filename.
 */
function parseFrontmatter(content) {
  const match = content.match(/^---\n([\s\S]*?)\n---/);
  if (!match) return { name: null, description: null };

  const block = match[1];
  const name        = (block.match(/^name:\s*(.+)$/m)        || [])[1]?.trim() || null;
  const description = (block.match(/^description:\s*(.+)$/m) || [])[1]?.trim() || null;

  return { name, description };
}

/**
 * Builds the AGENT_ROSTER.md content from the list of installed agents.
 * Each agent entry reads the written .md file to extract frontmatter.
 */
function buildRoster(agents, agentsDir) {
  const lines = [
    '# Agent Roster',
    '',
    'This file is auto-generated by `aiteam`. Do not edit manually.',
    '',
  ];

  for (const agent of agents) {
    const filename = path.basename(agent.file);
    const filePath = path.join(agentsDir, filename);
    const content  = fs.readFileSync(filePath, 'utf8');
    const { name, description } = parseFrontmatter(content);

    const displayName = name || agent.id;
    lines.push(`## ${displayName}`);
    lines.push('');
    lines.push(`- **ID:** ${agent.id}`);
    if (agent.role) lines.push(`- **Role:** ${agent.role}`);
    lines.push(`- **File:** .claude/agents/${filename}`);
    if (description) {
      // description can be very long — truncate to first sentence for the roster
      const summary = description.split(/[.\n]/)[0].trim();
      lines.push(`- **Scope:** ${summary}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Writes AGENT_ROSTER.md to the project root.
 */
function writeRoster(agents, agentsDir) {
  const rosterContent = buildRoster(agents, agentsDir);
  const rosterPath = path.join(process.cwd(), 'AGENT_ROSTER.md');
  fs.writeFileSync(rosterPath, rosterContent, 'utf8');
  return rosterContent;
}

module.exports = { buildRoster, writeRoster };
